language: php

os: linux

php:
  - '7.0'
  - '7.1'

before_script:
  - cp .env.travis .env
  - sudo apt install php-mongodb
  - mysql -e 'create database alterbit;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

  script:
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers