language: php

php:
- '7.1'

services:
- mongodb
- mysql

before_install:
- pecl install mongodb
- composer self-update

install: 
- composer install --no-interaction

before_script:
- phpenv rehash
- cp .env.travis .env
- mysql -e 'create database alterbit;'
- php artisan key:generate
